apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kube-vip.name" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  selector:
    matchLabels:
      {{- include "kube-vip.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-vip.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
          - manager
        env:
          - name: vip_interface
            value: {{ .Values.config.vip_interface | quote }}
          {{- if eq .Values.config.cp_enable "true" }}
          - name: vip_address
            value: {{ required "A valid config.vip_address required!" .Values.config.vip_address}}
          {{- end }}
          - name: vip_arp
            value: {{ .Values.config.vip_arp | quote }}
          - name: port
            value: {{ .Values.config.port | quote }}
          - name: cp_namespace
            value: {{ .Release.Namespace }}
          - name: vip_cidr
            value: {{ .Values.config.vip_cidr | quote }}
          - name: cp_enable
            value: {{ .Values.config.cp_enable | quote }}
          - name: svc_enable
            value: {{ .Values.config.svc_enable | quote }}
          - name: vip_startleader
            value: {{ .Values.config.vip_startleader | quote }}
          - name: vip_addpeerstolb
            value: {{ .Values.config.vip_addpeerstolb | quote }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: kube-vip
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      hostNetwork: true
      serviceAccountName: {{ include "kube-vip.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
